# Generated by Django 3.1.3 on 2021-07-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210710_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='created_on',
            new_name='followed_on',
        ),
    ]
